import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aaa ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <span>LOGO</span>
          <a href="#">Home</a>
          <a href="#">A</a>
          <a href="#">B</a>
          <a href="#">C</a>
        </nav>
        {children}
      </body>
    </html>
  )
}
